import type { ExecuteNaturalLanguageCommandUseCase } from '../modules/admin-command-bar/application/use-cases/ExecuteNaturalLanguageCommandUseCase';
import type { ExecuteBrainToolUseCase } from '../modules/admin-command-bar/application/use-cases/ExecuteBrainToolUseCase';
import type { GetAgentRunUseCase } from '../modules/admin-command-bar/application/use-cases/GetAgentRunUseCase';
import type { ResumeBrainAgentRunUseCase } from '../ai/intelligence/command-brain/ResumeBrainAgentRunUseCase';
import type { AgentRuntimePort } from '../ai/intelligence/agent-runtime/AgentRuntimePort';
import type { PersonalBrainRegistry } from '../ai/intelligence/personal-brain/PersonalBrainRegistry';
import type { GlobalBrainPort } from '../ai/intelligence/global-brain/GlobalBrainPort';
import type { GlobalKnowledgeAdminService } from '../ai/intelligence/global-knowledge/GlobalKnowledgeAdminService';
import type { GlobalKnowledgeService } from '../ai/intelligence/global-knowledge/GlobalKnowledgeService';
import type { KnowledgeDistillationService } from '../ai/intelligence/global-knowledge/distillation/KnowledgeDistillationService';
import type { CrossTenantSubmitPipeline } from '../ai/intelligence/global-knowledge/federated/FederatedQueryUseCase';
import type { KnowledgeTransferPort } from '../ai/intelligence/knowledge-transfer/KnowledgeTransferPort';
import type { KnowledgeContributionService } from '../ai/intelligence/knowledge-transfer/contribution/KnowledgeContributionService';
import type { ContributionHistoryService } from '../ai/intelligence/knowledge-transfer/contribution/ContributionHistoryService';
import type { SecAggRoundService } from '../ai/intelligence/global-knowledge/secure-aggregation/SecAggRoundService';
import type { LoRAAdapterRegistryPort } from '../ai/intelligence/personal-brain/LoRAAdapterRegistryPort';
import type { BrainMemoryService } from '../ai/intelligence/brain-memory/BrainMemoryService';
import type { CommandBrainService } from '../ai/intelligence/command-brain/CommandBrainService';
import type { SuggestionService } from '../modules/admin-command-bar/application/services/SuggestionService';
import type { UiAdoptionMetricsService } from '../modules/admin-command-bar/application/services/UiAdoptionMetricsService';
import type { HandoffOverviewService } from '../modules/admin-command-bar/application/services/HandoffOverviewService';
import type { ProactiveSuggestionService } from '../ai/intelligence/proactive/ProactiveSuggestionService';
import type { ProactiveLearningService } from '../ai/intelligence/proactive/learning/ProactiveLearningService';
import type { ProactiveEnrichmentService } from '../ai/intelligence/proactive/enrichment/ProactiveEnrichmentService';
import type { ProactiveAutoExecuteService } from '../ai/intelligence/proactive/execution/ProactiveAutoExecuteService';
import type { UndoCommandUseCase } from '../modules/admin-command-bar/application/use-cases/UndoCommandUseCase';
import type { UpdateInventoryUseCase } from '../modules/inventory-pricing/application/use-cases/UpdateInventoryUseCase';
import type { ListInventoryUseCase } from '../modules/inventory-pricing/application/use-cases/ListInventoryUseCase';
import type { AdjustInventoryUseCase } from '../modules/inventory-pricing/application/use-cases/AdjustInventoryUseCase';
import type { ApplyDynamicPriceUseCase } from '../modules/inventory-pricing/application/use-cases/ApplyDynamicPriceUseCase';
import type { SupplierMonitorPort } from '../modules/admin-command-bar/application/ports/SupplierMonitorPort';
import type { AdminDataPort } from '../modules/admin-command-bar/application/ports/AdminDataPort';
import type { CommandLogPort } from '../modules/admin-command-bar/application/ports/CommandLogPort';
import type { ListProductsUseCase } from '../modules/product-catalog/application/use-cases/ListProductsUseCase';
import type { CreateProductUseCase } from '../modules/product-catalog/application/use-cases/CreateProductUseCase';
import type { GetProductUseCase } from '../modules/product-catalog/application/use-cases/GetProductUseCase';
import type { UpdateProductUseCase } from '../modules/product-catalog/application/use-cases/UpdateProductUseCase';
import type { DeleteProductUseCase } from '../modules/product-catalog/application/use-cases/DeleteProductUseCase';
import type { ListProductVariantsUseCase } from '../modules/product-catalog/application/use-cases/ListProductVariantsUseCase';
import type { CreateProductVariantUseCase } from '../modules/product-catalog/application/use-cases/CreateProductVariantUseCase';
import type { UpdateProductVariantUseCase } from '../modules/product-catalog/application/use-cases/UpdateProductVariantUseCase';
import type { DeleteProductVariantUseCase } from '../modules/product-catalog/application/use-cases/DeleteProductVariantUseCase';
import type { UploadProductMediaUseCase } from '../modules/product-catalog/application/use-cases/UploadProductMediaUseCase';
import type { SiteRepository } from '../modules/storefront-builder/domain/repositories/SiteRepository';
import type { ArtifactStorePort } from '../modules/storefront-builder/application/ports/ArtifactStorePort';
import type { CodegenCompilerPort } from '../modules/storefront-builder/application/ports/CodegenCompilerPort';
import type { PreviewHostPort } from '../modules/storefront-builder/application/ports/PreviewHostPort';
import type { DeployPort } from '../modules/storefront-builder/application/ports/DeployPort';
import type { StorefrontCatalogPort } from '../modules/storefront-builder/application/ports/StorefrontCatalogPort';
import type { CreateSiteProjectUseCase } from '../modules/storefront-builder/application/use-cases/CreateSiteProjectUseCase';
import type { GetSiteProjectUseCase } from '../modules/storefront-builder/application/use-cases/GetSiteProjectUseCase';
import type { ListSiteProjectsUseCase } from '../modules/storefront-builder/application/use-cases/ListSiteProjectsUseCase';
import type { CreateRevisionUseCase } from '../modules/storefront-builder/application/use-cases/CreateRevisionUseCase';
import type { ListRevisionsUseCase } from '../modules/storefront-builder/application/use-cases/ListRevisionsUseCase';
import type { GetRevisionUseCase } from '../modules/storefront-builder/application/use-cases/GetRevisionUseCase';
import type { ListPagesUseCase } from '../modules/storefront-builder/application/use-cases/ListPagesUseCase';
import type { GetPageUseCase } from '../modules/storefront-builder/application/use-cases/GetPageUseCase';
import type { UpdatePageCopyUseCase } from '../modules/storefront-builder/application/use-cases/UpdatePageCopyUseCase';
import type { StartBuildUseCase } from '../modules/storefront-builder/application/use-cases/StartBuildUseCase';
import type { HealBrokenLiveSitesUseCase } from '../modules/storefront-builder/application/use-cases/HealBrokenLiveSitesUseCase';
import type { ApplyBuildWallTriggerUseCase } from '../modules/storefront-builder/application/use-cases/ApplyBuildWallTriggerUseCase';
import type { GetBuildJobUseCase } from '../modules/storefront-builder/application/use-cases/GetBuildJobUseCase';
import type { ProposePublishUseCase } from '../modules/storefront-builder/application/use-cases/ProposePublishUseCase';
import type { GetDeployTargetUseCase } from '../modules/storefront-builder/application/use-cases/GetDeployTargetUseCase';
import type { UpsertDeployTargetUseCase } from '../modules/storefront-builder/application/use-cases/UpsertDeployTargetUseCase';
import type { GetPreviewUrlUseCase } from '../modules/storefront-builder/application/use-cases/GetPreviewUrlUseCase';
import type { ResolveStorefrontSiteUseCase } from '../modules/storefront-builder/application/use-cases/ResolveStorefrontSiteUseCase';
import type { GetStorefrontCatalogUseCase } from '../modules/storefront-builder/application/use-cases/GetStorefrontCatalogUseCase';
import type { GetStorefrontProductUseCase } from '../modules/storefront-builder/application/use-cases/GetStorefrontProductUseCase';
import type { GetStorefrontPageUseCase } from '../modules/storefront-builder/application/use-cases/GetStorefrontPageUseCase';
import type { CartRepository } from '../modules/storefront-builder/domain/repositories/CartRepository';
import type { CheckoutIdempotencyPort } from '../modules/storefront-builder/application/ports/CheckoutIdempotencyPort';
import type { CreateCartUseCase } from '../modules/storefront-builder/application/use-cases/CreateCartUseCase';
import type { GetCartUseCase } from '../modules/storefront-builder/application/use-cases/GetCartUseCase';
import type { AddCartItemUseCase } from '../modules/storefront-builder/application/use-cases/AddCartItemUseCase';
import type { UpdateCartItemUseCase } from '../modules/storefront-builder/application/use-cases/UpdateCartItemUseCase';
import type { RemoveCartItemUseCase } from '../modules/storefront-builder/application/use-cases/RemoveCartItemUseCase';
import type { CheckoutCartUseCase } from '../modules/storefront-builder/application/use-cases/CheckoutCartUseCase';
import type { CreateOrderUseCase } from '../modules/order-management/application/use-cases/CreateOrderUseCase';
import type { OrderRepository } from '../modules/order-management/domain/repositories/OrderRepository';
import type { UpdateOrderStatusUseCase } from '../modules/order-management/application/use-cases/UpdateOrderStatusUseCase';
import type { GetOrderDetailUseCase } from '../modules/order-management/application/use-cases/GetOrderDetailUseCase';
import type { ShipOrderUseCase } from '../modules/order-management/application/use-cases/ShipOrderUseCase';
import type { CreateOrderRefundUseCase } from '../modules/order-management/application/use-cases/CreateOrderRefundUseCase';
import type { ListCustomersUseCase } from '../modules/customers/application/use-cases/ListCustomersUseCase';
import type { GetCustomerUseCase } from '../modules/customers/application/use-cases/GetCustomerUseCase';
import type { ListCustomerOrdersUseCase } from '../modules/customers/application/use-cases/ListCustomerOrdersUseCase';
import type { ListPromotionsUseCase } from '../modules/promotions/application/use-cases/ListPromotionsUseCase';
import type { CreatePromotionUseCase } from '../modules/promotions/application/use-cases/CreatePromotionUseCase';
import type { ListDecisionsUseCase } from '../modules/autonomous-operations/application/use-cases/DecisionUseCases';
import type { CreateDecisionUseCase } from '../modules/autonomous-operations/application/use-cases/DecisionUseCases';
import type { GetDecisionUseCase } from '../modules/autonomous-operations/application/use-cases/DecisionUseCases';
import type { RespondToOfferUseCase } from '../modules/agentic-commerce/application/use-cases/RespondToOfferUseCase';
import type { NegotiationSessionOrchestrator } from '../ai/intelligence/multi-agent/negotiation/NegotiationSessionOrchestrator';
import type { StartNegotiationUseCase } from '../modules/agentic-commerce/application/use-cases/StartNegotiationUseCase';
import type { GetNegotiationUseCase } from '../modules/agentic-commerce/application/use-cases/StartNegotiationUseCase';
import type { ListActiveNegotiationsUseCase } from '../modules/agentic-commerce/application/use-cases/StartNegotiationUseCase';
import type { SupplierDecisionEngine } from '../modules/supplier-intelligence/application/services/SupplierDecisionEngine';
import type { SupplierRepository } from '../modules/supplier-intelligence/domain/repositories/SupplierRepository';
import type { SupplierOverviewService } from '../modules/supplier-intelligence/application/services/SupplierOverviewService';
import type { SupplierChangePort } from '../modules/supplier-intelligence/application/ports/SupplierChangePort';
import type { MonitorSupplierUseCase } from '../modules/supplier-intelligence/application/use-cases/MonitorSupplierUseCase';
import type { MonitorLowStockUseCase } from '../modules/inventory-pricing/application/use-cases/MonitorLowStockUseCase';
import type { SupplierWebhookAdapter } from '../modules/supplier-intelligence/infrastructure/adapters/SupplierWebhookAdapter';
import type { PaymentService } from '../modules/payment-fulfillment/application/services/PaymentService';
import type { PaymentRepository } from '../modules/payment-fulfillment/domain/repositories/PaymentRepository';
import type { ProcessPaymentUseCase } from '../modules/payment-fulfillment/application/use-cases/ProcessPaymentUseCase';
import type { FulfillmentService } from '../modules/payment-fulfillment/application/services/FulfillmentService';
import type { PrismaFulfillmentAdapter } from '../modules/payment-fulfillment/infrastructure/adapters/PrismaFulfillmentAdapter';
import type { SubmitInsightUseCase } from '../modules/zero-knowledge-hive-mind/application/use-cases/SubmitInsightUseCase';
import type { QueryInsightsUseCase } from '../modules/zero-knowledge-hive-mind/application/use-cases/QueryInsightsUseCase';
import type { PrismaEmailRepository } from '../modules/aether-mail/infrastructure/persistence/PrismaEmailRepository';
import type { PrismaMerchantCoOwnershipAdapter } from '../modules/merchant-co-ownership/infrastructure/adapters/PrismaMerchantCoOwnershipAdapter';
import type { PrismaPhysicalLocationAdapter } from '../modules/physical-digital-symbiosis/infrastructure/adapters/PrismaPhysicalLocationAdapter';
import type { SelfEvolvingPort } from '../modules/self-evolving-codebase/application/ports/SelfEvolvingPort';
import type { ManagePersonalBrainMemoryUseCase } from '../modules/admin-command-bar/application/use-cases/ManagePersonalBrainMemoryUseCase';
import type { GetReflectionTimelineUseCase } from '../modules/admin-command-bar/application/use-cases/GetReflectionTimelineUseCase';
import type { ManageReflectionExperimentsUseCase } from '../modules/admin-command-bar/application/use-cases/ManageReflectionExperimentsUseCase';
import type { AgentSupervisorPort } from '../ai/intelligence/multi-agent/AgentSupervisorPort';
import type { ReflectionDistillationService } from '../ai/intelligence/global-knowledge/distillation/ReflectionDistillationService';
import type { ReflectionExperimentService } from '../ai/intelligence/personal-brain/reflection/experiments/ReflectionExperimentService';
import type { ReflectionMetricsRecorder } from '../ai/intelligence/personal-brain/reflection/ReflectionMetricsRecorder';
import type { BilateralExchangeService } from '../modules/bilateral-exchange/application/BilateralExchangeService';
import type { GoalService } from '../ai/intelligence/goals/GoalService';
import type { GoalProgressService } from '../ai/intelligence/goals/GoalProgressService';
import type { GoalContextProvider } from '../ai/intelligence/goals/GoalContextProvider';
import type { GoalRepository } from '../ai/intelligence/goals/GoalRepository';
import type { GoalSuggestionEngine } from '../ai/intelligence/goals/suggestions/GoalSuggestionEngine';

export interface AppCompositionRoot {
  executeNaturalLanguageCommand: ExecuteNaturalLanguageCommandUseCase;
  executeBrainTool: ExecuteBrainToolUseCase;
  getAgentRun: GetAgentRunUseCase;
  resumeBrainAgentRun?: ResumeBrainAgentRunUseCase;
  agentRuntime: AgentRuntimePort;
  personalBrainRegistry: PersonalBrainRegistry;
  globalBrain: GlobalBrainPort;
  /** Honest GlobalBrain mode for /health (`placeholder` | `hive-mind`). */
  globalBrainMode: 'placeholder' | 'hive-mind';
  globalKnowledgeService: GlobalKnowledgeService;
  globalKnowledgeAdminService: GlobalKnowledgeAdminService;
  knowledgeDistillationService: KnowledgeDistillationService;
  crossTenantSubmitPipeline: CrossTenantSubmitPipeline;
  knowledgeTransfer: KnowledgeTransferPort;
  knowledgeContributionService: KnowledgeContributionService;
  contributionHistoryService: ContributionHistoryService;
  secAggRoundService: SecAggRoundService;
  loraRegistry: LoRAAdapterRegistryPort;
  brainMemoryService: BrainMemoryService;
  commandBrainService?: CommandBrainService;
  suggestionService: SuggestionService;
  uiAdoptionMetricsService: UiAdoptionMetricsService;
  handoffOverviewService: HandoffOverviewService;
  proactiveSuggestionService: ProactiveSuggestionService;
  proactiveLearningService: ProactiveLearningService;
  proactiveEnrichmentService: ProactiveEnrichmentService;
  proactiveAutoExecuteService: ProactiveAutoExecuteService;
  undoCommandUseCase: UndoCommandUseCase;
  updateInventory: UpdateInventoryUseCase;
  listInventory: ListInventoryUseCase;
  adjustInventory: AdjustInventoryUseCase;
  applyDynamicPrice: ApplyDynamicPriceUseCase;
  supplierMonitor: SupplierMonitorPort;
  adminData: AdminDataPort;
  commandLog: CommandLogPort;
  listProducts: ListProductsUseCase;
  createProduct: CreateProductUseCase;
  getProduct: GetProductUseCase;
  updateProduct: UpdateProductUseCase;
  deleteProduct: DeleteProductUseCase;
  listProductVariants: ListProductVariantsUseCase;
  createProductVariant: CreateProductVariantUseCase;
  updateProductVariant: UpdateProductVariantUseCase;
  deleteProductVariant: DeleteProductVariantUseCase;
  uploadProductMedia: UploadProductMediaUseCase;
  /** Storefront builder (P02/P03) — admin HTTP at /api/website; public read at /api/storefront (P04). */
  siteRepository: SiteRepository;
  storefrontArtifactStore: ArtifactStorePort;
  storefrontCodegenCompiler: CodegenCompilerPort;
  storefrontPreviewHost: PreviewHostPort;
  storefrontDeploy: DeployPort;
  storefrontCatalog: StorefrontCatalogPort;
  createSiteProject: CreateSiteProjectUseCase;
  getSiteProject: GetSiteProjectUseCase;
  listSiteProjects: ListSiteProjectsUseCase;
  createSiteRevision: CreateRevisionUseCase;
  listSiteRevisions: ListRevisionsUseCase;
  getSiteRevision: GetRevisionUseCase;
  listSitePages: ListPagesUseCase;
  getSitePage: GetPageUseCase;
  updateSitePageCopy: UpdatePageCopyUseCase;
  startSiteBuild: StartBuildUseCase;
  healBrokenLiveSites: HealBrokenLiveSitesUseCase;
  applyBuildWallTrigger: ApplyBuildWallTriggerUseCase;
  getSiteBuildJob: GetBuildJobUseCase;
  proposeSitePublish: ProposePublishUseCase;
  getSiteDeployTarget: GetDeployTargetUseCase;
  upsertSiteDeployTarget: UpsertDeployTargetUseCase;
  getSitePreviewUrl: GetPreviewUrlUseCase;
  resolveStorefrontSite: ResolveStorefrontSiteUseCase;
  getStorefrontCatalog: GetStorefrontCatalogUseCase;
  getStorefrontProduct: GetStorefrontProductUseCase;
  getStorefrontPage: GetStorefrontPageUseCase;
  cartRepository: CartRepository;
  storefrontCheckoutIdempotency: CheckoutIdempotencyPort;
  createStorefrontCart: CreateCartUseCase;
  getStorefrontCart: GetCartUseCase;
  addStorefrontCartItem: AddCartItemUseCase;
  updateStorefrontCartItem: UpdateCartItemUseCase;
  removeStorefrontCartItem: RemoveCartItemUseCase;
  checkoutStorefrontCart: CheckoutCartUseCase;
  createOrder: CreateOrderUseCase;
  orderRepository: OrderRepository;
  updateOrderStatus: UpdateOrderStatusUseCase;
  getOrderDetail: GetOrderDetailUseCase;
  shipOrder: ShipOrderUseCase;
  createOrderRefund: CreateOrderRefundUseCase;
  listCustomers: ListCustomersUseCase;
  getCustomer: GetCustomerUseCase;
  listCustomerOrders: ListCustomerOrdersUseCase;
  listPromotions: ListPromotionsUseCase;
  createPromotion: CreatePromotionUseCase;
  listDecisions: ListDecisionsUseCase;
  createDecision: CreateDecisionUseCase;
  getDecision: GetDecisionUseCase;
  respondToOffer: RespondToOfferUseCase;
  negotiationSessionOrchestrator?: NegotiationSessionOrchestrator;
  startNegotiation: StartNegotiationUseCase;
  getNegotiation: GetNegotiationUseCase;
  listActiveNegotiations: ListActiveNegotiationsUseCase;
  supplierDecisionEngine: SupplierDecisionEngine;
  supplierRepository: SupplierRepository;
  supplierOverviewService: SupplierOverviewService;
  supplierChangePort: SupplierChangePort;
  emailRepository: PrismaEmailRepository;
  monitorSupplierUseCase: MonitorSupplierUseCase;
  monitorLowStockUseCase: MonitorLowStockUseCase;
  supplierWebhook: SupplierWebhookAdapter;
  paymentService: PaymentService;
  paymentRepository: PaymentRepository;
  processPayment: ProcessPaymentUseCase;
  fulfillmentService: FulfillmentService;
  persistFulfillment: PrismaFulfillmentAdapter;
  submitInsight: SubmitInsightUseCase;
  queryInsights: QueryInsightsUseCase;
  merchantCoOwnership: PrismaMerchantCoOwnershipAdapter;
  physicalLocations: PrismaPhysicalLocationAdapter;
  selfEvolving: SelfEvolvingPort;
  processIncomingEmailUseCase: import('../modules/aether-mail/application/use-cases/ProcessIncomingEmailUseCase').ProcessIncomingEmailUseCase;
  managePersonalBrainMemory: ManagePersonalBrainMemoryUseCase;
  getReflectionTimeline: GetReflectionTimelineUseCase;
  manageReflectionExperiments: ManageReflectionExperimentsUseCase;
  agentSupervisor?: AgentSupervisorPort;
  peerDelegationBridge?: import('../ai/intelligence/multi-agent/peer/PeerDelegationBridge').PeerDelegationBridge;
  federatedExecutionWorker?: import('../ai/intelligence/multi-agent/peer/federated/FederatedExecutionWorker').FederatedExecutionWorker;
  agentPatternSync?: import('../ai/intelligence/global-knowledge/agent-patterns/AgentPatternSyncService').AgentPatternSyncService;
  reflectionDistillationService?: ReflectionDistillationService;
  reflectionExperimentService?: ReflectionExperimentService;
  reflectionMetricsRecorder?: ReflectionMetricsRecorder;
  memoryConsolidationJob: import('../ai/intelligence/personal-brain/memory/jobs/MemoryConsolidationJob').MemoryConsolidationJob;
  strategicReflectionJob: import('../ai/intelligence/personal-brain/reflection/jobs/StrategicReflectionJob').StrategicReflectionJob;
  runMemoryGcJob?: import('../ai/intelligence/multi-agent/memory/jobs/RunMemoryGcJob').RunMemoryGcJob;
  runWorkingMemory?: import('../ai/intelligence/multi-agent/memory/RunWorkingMemoryPort').RunWorkingMemoryPort;
  bilateralExchangeService: BilateralExchangeService;
  goalService: GoalService;
  goalProgressService: GoalProgressService;
  goalContextProvider: GoalContextProvider;
  goalRepository: GoalRepository;
  goalSuggestionEngine?: GoalSuggestionEngine;
  agentRegistry?: import('../ai/intelligence/multi-agent/AgentRegistry').AgentRegistry;
  agentRosterService?: import('../modules/admin-command-bar/application/services/AgentRosterService').AgentRosterService;
  activityFeedService: import('../modules/admin-command-bar/application/services/ActivityFeedService').ActivityFeedService;
  overviewFeedService: import('../modules/admin-command-bar/application/services/OverviewFeedService').OverviewFeedService;
  overviewFeedWriter: import('../modules/admin-command-bar/application/services/OverviewFeedWriter').OverviewFeedWriterService;
  overviewNotificationDispatcher: import('../modules/admin-command-bar/application/services/OverviewNotificationDispatcher').OverviewNotificationDispatcher;
  notificationWriter: import('../modules/admin-command-bar/application/services/notifications/NotificationWriter').NotificationWriterService;
  notificationInboxService: import('../modules/admin-command-bar/application/services/NotificationInboxService').NotificationInboxService;
  notificationReadStateService: import('../modules/admin-command-bar/application/services/NotificationReadStateService').NotificationReadStateService;
  notificationBackfillJob: import('../modules/admin-command-bar/application/services/jobs/NotificationBackfillJob').NotificationBackfillJob;
  notificationDigestJob: import('../modules/admin-command-bar/application/services/jobs/NotificationDigestJob').NotificationDigestJob;
  overviewDigestJob: import('../modules/admin-command-bar/application/services/jobs/OverviewDigestJob').OverviewDigestJob;
  overviewFeedBackfillJob: import('../modules/admin-command-bar/application/services/jobs/OverviewFeedBackfillJob').OverviewFeedBackfillJob;
}
