import type { DesignTokens } from './sitePlanSchema';

/**
 * Deterministic CSS custom properties from design tokens.
 * Key order is fixed so identical tokens → identical CSS.
 */
type TokenBag = DesignTokens & {
  color?: { primary?: string; accent?: string; bg?: string; text?: string };
  font?: { display?: string; body?: string };
};

function resolveRadius(radius: unknown): string {
  if (radius === undefined || radius === null) return '0.5rem';
  if (typeof radius === 'number') return `${radius}px`;
  if (typeof radius === 'string') return radius;
  if (
    typeof radius === 'object' &&
    typeof (radius as { md?: unknown }).md === 'string'
  ) {
    return (radius as { md: string }).md;
  }
  return '0.5rem';
}

export function tokensToCss(tokens: DesignTokens): string {
  const t = tokens as TokenBag;
  const appendixColor = t.color;
  const colors = {
    primary:
      tokens.colors?.primary ?? tokens.primary ?? appendixColor?.primary ?? '#1a1a1a',
    accent: tokens.colors?.accent ?? tokens.accent ?? appendixColor?.accent ?? '#c4a484',
    background:
      tokens.colors?.background ??
      tokens.background ??
      appendixColor?.bg ??
      '#faf9f7',
    foreground:
      tokens.colors?.foreground ??
      tokens.foreground ??
      appendixColor?.text ??
      '#1a1a1a',
    muted: tokens.colors?.muted ?? tokens.muted ?? '#6b6b6b',
  };

  const fontFamily =
    tokens.typography?.fontFamily ??
    t.font?.display ??
    'Georgia, "Times New Roman", serif';
  const fontSizeBase = tokens.typography?.fontSizeBase ?? '16px';
  const radius = resolveRadius(tokens.radius);

  const lines: string[] = [
    '/* Generated by AllowlistCodegenCompiler — do not edit */',
    ':root {',
    `  --color-primary: ${colors.primary};`,
    `  --color-accent: ${colors.accent};`,
    `  --color-background: ${colors.background};`,
    `  --color-foreground: ${colors.foreground};`,
    `  --color-muted: ${colors.muted};`,
    `  --font-family: ${fontFamily};`,
    `  --font-size-base: ${fontSizeBase};`,
    `  --radius: ${radius};`,
  ];

  const scale = tokens.typography?.scale;
  if (scale) {
    for (const key of Object.keys(scale).sort()) {
      lines.push(`  --font-size-${key}: ${scale[key]};`);
    }
  }

  const spacing = tokens.spacing;
  if (spacing) {
    for (const key of Object.keys(spacing).sort()) {
      const value = spacing[key];
      const cssValue = typeof value === 'number' ? `${value}px` : value;
      lines.push(`  --spacing-${key}: ${cssValue};`);
    }
  }

  lines.push('}', '');
  return lines.join('\n');
}

/** Flatten tokens for tokens.json + public site resolve. */
export function normalizeTokensJson(tokens: DesignTokens): Record<string, unknown> {
  const t = tokens as TokenBag;
  const primary =
    tokens.colors?.primary ?? tokens.primary ?? t.color?.primary ?? '#1a1a1a';
  const accent = tokens.colors?.accent ?? tokens.accent ?? t.color?.accent ?? '#c4a484';
  const background =
    tokens.colors?.background ?? tokens.background ?? t.color?.bg ?? '#faf9f7';
  const foreground =
    tokens.colors?.foreground ?? tokens.foreground ?? t.color?.text ?? '#1a1a1a';
  const muted = tokens.colors?.muted ?? tokens.muted ?? '#6b6b6b';

  return {
    primary,
    accent,
    background,
    foreground,
    muted,
    colors: {
      primary,
      accent,
      background,
      foreground,
      muted,
      ...(tokens.colors ?? {}),
    },
    ...(tokens.typography ? { typography: tokens.typography } : {}),
    ...(tokens.spacing ? { spacing: tokens.spacing } : {}),
    ...(tokens.radius !== undefined ? { radius: tokens.radius } : {}),
  };
}
