import type { DemoIntentId, DemoSuggestion, SuggestionCategory } from './types';

export const DEMO_SUGGESTIONS: DemoSuggestion[] = [
  {
    id: 'pricing-week',
    label: 'Optimaliseer prijzen deze week',
    command: 'Optimaliseer mijn prijzen deze week',
    intentId: 'PRICING_OPTIMIZATION',
    category: 'prijs',
    hint: "3 SKU's met veilige marge-verhoging",
    executionMode: 'autonomous',
  },
  {
    id: 'earbuds-proposal',
    label: 'Prijsvoorstel Wireless Earbuds Pro',
    command: 'Maak een prijsvoorstel voor Wireless Earbuds Pro',
    intentId: 'PRODUCT_PRICE_PROPOSAL',
    category: 'prijs',
    hint: 'Product-specifiek voorstel op basis van markt',
    executionMode: 'autonomous',
  },
  {
    id: 'supplier-drops',
    label: 'Check leveranciers op prijsdalingen',
    command: 'Check leveranciers op prijsdalingen',
    intentId: 'SUPPLIER_CHECK',
    category: 'leverancier',
    hint: 'Inkoopdalingen en sync-voorbereiding',
    executionMode: 'autonomous',
  },
  {
    id: 'high-risk',
    label: 'Toon high-risk goedkeuringen',
    command: 'Toon high-risk goedkeuringen',
    intentId: 'HIGH_RISK_APPROVALS',
    category: 'goedkeuringen',
    hint: '4 items wachten op jouw besluit',
    executionMode: 'approval_required',
  },
  {
    id: 'margin-category',
    label: 'Toon marge per categorie',
    command: 'Toon marge per categorie',
    intentId: 'MARGIN_INSIGHT',
    category: 'inzicht',
    hint: 'Breakdown per productcategorie',
    executionMode: 'inform_only',
  },
  {
    id: 'autonomous-pricing',
    label: 'Voer low-risk prijsaanpassingen uit',
    command: 'Voer low-risk prijsaanpassingen automatisch uit',
    intentId: 'AUTONOMOUS_ACTION',
    category: 'autonomie',
    hint: "3 SKU's zonder goedkeuring, rollback 24u",
    executionMode: 'autonomous',
  },
  {
    id: 'business-week',
    label: 'Hoe presteert mijn business deze week?',
    command: 'Hoe presteert mijn business deze week?',
    intentId: 'BUSINESS_SUMMARY',
    category: 'overzicht',
    hint: 'Omzet, orders en marge vs. vorige week',
    executionMode: 'inform_only',
  },
  {
    id: 'insights-today',
    label: 'Wat staat vandaag klaar?',
    command: 'Wat staat vandaag klaar voor mij?',
    intentId: 'INSIGHTS_OVERVIEW',
    category: 'overzicht',
    hint: 'Alle voorbereide acties in één overzicht',
  },
  {
    id: 'compound-earbuds-nordic',
    label: 'Prijzen + Nordic sync',
    command: 'Optimaliseer prijzen voor Wireless Earbuds en sync daarna de voorraad bij Nordic',
    intentId: 'COMPOUND_WORKFLOW',
    category: 'prijs',
    hint: '2 stappen: prijsoptimalisatie → leverancierssync',
    executionMode: 'autonomous',
  },
  {
    id: 'compound-pricing-supplier',
    label: 'Optimaliseer prijzen en check leveranciers',
    command: 'Optimaliseer mijn prijzen deze week en check daarna leveranciers',
    intentId: 'COMPOUND_WORKFLOW',
    category: 'overzicht',
    hint: 'Multi-step workflow met tussentijdse feedback',
    executionMode: 'autonomous',
  },
  {
    id: 'compound-approvals-margin',
    label: 'Goedkeuringen + marge-inzicht',
    command: 'Toon high-risk goedkeuringen en toon daarna marge per categorie',
    intentId: 'COMPOUND_WORKFLOW',
    category: 'goedkeuringen',
    hint: '2 stappen: beslissen → inzicht',
    executionMode: 'approval_required',
  },
  {
    id: 'compound-earbuds-check',
    label: 'Earbuds voorstel + leveranciers',
    command: 'Maak een prijsvoorstel voor Wireless Earbuds Pro en check daarna leveranciers',
    intentId: 'COMPOUND_WORKFLOW',
    category: 'prijs',
    hint: 'Productprijs gevolgd door inkoop-sync',
    executionMode: 'autonomous',
  },
];
export const IDLE_SUGGESTION_IDS = [
  'pricing-week',
  'supplier-drops',
  'margin-category',
  'high-risk',
  'autonomous-pricing',
  'business-week',
] as const;
