export class Product {
  constructor(
    public readonly id: string,
    public name: string,
    public description: string | null,
    public slug: string,
    public status: string,
    public readonly createdAt: Date,
    public updatedAt: Date
  ) {}

  static create(data: {
    name: string;
    description?: string;
    slug: string;
  }): Product {
    return new Product(
      '', // ID will be generated by database
      data.name,
      data.description || null,
      data.slug,
      'active',
      new Date(),
      new Date()
    );
  }
}