import {
  Bell,
  Bot,
  Brain,
  ClipboardList,
  CreditCard,
  Eye,
  FileText,
  Globe,
  History,
  LayoutDashboard,
  LayoutList,
  Package,
  Percent,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Target,
  Truck,
  Upload,
  Users,
  Warehouse,
} from 'lucide-react';
import { COMMAND_CENTER_PATH, type AppNavItem } from './routes.types';

/** Minimal app navigation — Command Bar remains primary for deeper routes. */
export const minimalNavItems: AppNavItem[] = [
  {
    to: COMMAND_CENTER_PATH,
    label: 'Command Center',
    labelKey: 'nav.commandCenter',
    icon: Sparkles,
    end: true,
  },
  {
    to: '/overview',
    label: 'AETHER Overzicht',
    labelKey: 'nav.overview',
    icon: LayoutDashboard,
  },
  { to: '/workstream', label: 'Vandaag', labelKey: 'nav.workstream', icon: LayoutList },
  { to: '/goals', label: 'Doelen', labelKey: 'nav.goals', icon: Target },
  { to: '/approvals', label: 'Goedkeuringen', labelKey: 'nav.approvals', icon: ShieldCheck },
  { to: '/insights', label: 'Inzichten', labelKey: 'nav.insights', icon: Brain },
  { to: '/agents', label: 'Agents', labelKey: 'nav.agents', icon: Bot },
  { to: '/timeline', label: 'Activiteit', labelKey: 'nav.timeline', icon: History },
  { to: '/notifications', label: 'Meldingen', labelKey: 'nav.notifications', icon: Bell },
  { to: '/suppliers', label: 'Leveranciers', labelKey: 'nav.suppliers', icon: Truck },
  {
    to: '/products',
    label: 'Producten',
    labelKey: 'nav.products',
    icon: Package,
    navGroup: 'commerce',
  },
  {
    to: '/orders',
    label: 'Bestellingen',
    labelKey: 'nav.orders',
    icon: ShoppingBag,
    navGroup: 'commerce',
  },
  {
    to: '/customers',
    label: 'Klanten',
    labelKey: 'nav.customers',
    icon: Users,
    navGroup: 'commerce',
  },
  {
    to: '/inventory',
    label: 'Voorraad',
    labelKey: 'nav.inventory',
    icon: Warehouse,
    navGroup: 'commerce',
  },
  {
    to: '/promotions',
    label: 'Promoties',
    labelKey: 'nav.promotions',
    icon: Percent,
    navGroup: 'commerce',
  },
  {
    to: '/payments',
    label: 'Betalingen',
    labelKey: 'nav.payments',
    icon: CreditCard,
    navGroup: 'commerce',
  },
  {
    to: '/website',
    label: 'Website',
    labelKey: 'nav.website',
    icon: Globe,
    end: true,
    navGroup: 'website',
  },
  {
    to: '/website/brief',
    label: 'Brief',
    labelKey: 'nav.websiteBrief',
    icon: ClipboardList,
    navGroup: 'website',
  },
  {
    to: '/website/preview',
    label: 'Preview',
    labelKey: 'nav.websitePreview',
    icon: Eye,
    navGroup: 'website',
  },
  {
    to: '/website/pages',
    label: 'Pagina’s',
    labelKey: 'nav.websitePages',
    icon: LayoutList,
    navGroup: 'website',
  },
  {
    to: '/website/publish',
    label: 'Publiceren',
    labelKey: 'nav.websitePublish',
    icon: Upload,
    navGroup: 'website',
  },
  {
    to: '/pages',
    label: 'CMS',
    labelKey: 'nav.pages',
    icon: FileText,
    navGroup: 'website',
  },
];
