import { commandCenterParent, type AppRouteDefinition } from './routes.types';

/** Website builder routes — brief, preview, pages, publish, CMS. */
export const websiteRoutes: AppRouteDefinition[] = [
  {
    path: '/website/brief',
    module: 'website',
    sidebarGroup: 'deep',
    layout: 'deep',
    inNav: true,
    navGroup: 'website',
    parentNav: { to: '/website', labelKey: 'nav.website' },
    skeleton: 'module',
    breadcrumbLabelKey: 'nav.websiteBrief',
  },
  {
    path: '/website/preview',
    module: 'website',
    sidebarGroup: 'deep',
    layout: 'deep',
    inNav: true,
    navGroup: 'website',
    parentNav: { to: '/website', labelKey: 'nav.website' },
    skeleton: 'module',
    breadcrumbLabelKey: 'nav.websitePreview',
  },
  {
    path: '/website/pages',
    module: 'website',
    sidebarGroup: 'deep',
    layout: 'deep',
    inNav: true,
    navGroup: 'website',
    parentNav: { to: '/website', labelKey: 'nav.website' },
    skeleton: 'list',
    breadcrumbLabelKey: 'nav.websitePages',
  },
  {
    path: '/website/publish',
    module: 'website',
    sidebarGroup: 'deep',
    layout: 'deep',
    inNav: true,
    navGroup: 'website',
    parentNav: { to: '/website', labelKey: 'nav.website' },
    skeleton: 'module',
    breadcrumbLabelKey: 'nav.websitePublish',
  },
  {
    path: '/website',
    module: 'website',
    sidebarGroup: 'deep',
    layout: 'deep',
    inNav: true,
    navGroup: 'website',
    parentNav: commandCenterParent,
    skeleton: 'module',
    breadcrumbLabelKey: 'nav.website',
  },
  {
    path: '/pages',
    module: 'website',
    sidebarGroup: 'deep',
    layout: 'deep',
    inNav: true,
    navGroup: 'website',
    parentNav: { to: '/website', labelKey: 'nav.website' },
    skeleton: 'list',
    breadcrumbLabelKey: 'nav.pages',
  },
];
