import { commandCenterParent, type AppRouteDefinition } from './routes.types';

/** Commerce module routes — products, orders, customers, inventory, promotions, payments. */
export const commerceRoutes: AppRouteDefinition[] = [
  {
    path: '/products',
    module: 'products',
    sidebarGroup: 'deep',
    layout: 'deep',
    inNav: true,
    navGroup: 'commerce',
    parentNav: commandCenterParent,
    skeleton: 'list',
    breadcrumbLabelKey: 'nav.products',
  },
  {
    path: '/products/new',
    module: 'products',
    sidebarGroup: 'deep',
    layout: 'deep',
    navGroup: 'commerce',
    parentNav: { to: '/products', labelKey: 'nav.products' },
    skeleton: 'module',
    breadcrumbLabelKey: 'nav.productNew',
  },
  {
    path: '/products/:id',
    module: 'products',
    sidebarGroup: 'deep',
    layout: 'deep',
    navGroup: 'commerce',
    parentNav: { to: '/products', labelKey: 'nav.products' },
    skeleton: 'module',
    breadcrumbLabelKey: 'nav.productDetail',
  },
  {
    path: '/orders',
    module: 'orders',
    sidebarGroup: 'deep',
    layout: 'deep',
    inNav: true,
    navGroup: 'commerce',
    parentNav: commandCenterParent,
    skeleton: 'list',
    breadcrumbLabelKey: 'nav.orders',
  },
  {
    path: '/orders/:id',
    module: 'orders',
    sidebarGroup: 'deep',
    layout: 'deep',
    navGroup: 'commerce',
    parentNav: { to: '/orders', labelKey: 'nav.orders' },
    skeleton: 'module',
    breadcrumbLabelKey: 'nav.orderDetail',
  },
  {
    path: '/customers',
    module: 'customers',
    sidebarGroup: 'deep',
    layout: 'deep',
    inNav: true,
    navGroup: 'commerce',
    parentNav: commandCenterParent,
    skeleton: 'list',
    breadcrumbLabelKey: 'nav.customers',
  },
  {
    path: '/customers/:id',
    module: 'customers',
    sidebarGroup: 'deep',
    layout: 'deep',
    navGroup: 'commerce',
    parentNav: { to: '/customers', labelKey: 'nav.customers' },
    skeleton: 'module',
    breadcrumbLabelKey: 'nav.customerDetail',
  },
  {
    path: '/inventory',
    module: 'inventory',
    sidebarGroup: 'deep',
    layout: 'deep',
    inNav: true,
    navGroup: 'commerce',
    parentNav: commandCenterParent,
    skeleton: 'list',
    breadcrumbLabelKey: 'nav.inventory',
  },
  {
    path: '/promotions',
    module: 'promotions',
    sidebarGroup: 'deep',
    layout: 'deep',
    inNav: true,
    navGroup: 'commerce',
    parentNav: commandCenterParent,
    skeleton: 'list',
    breadcrumbLabelKey: 'nav.promotions',
  },
  {
    path: '/payments',
    module: 'payments',
    sidebarGroup: 'deep',
    layout: 'deep',
    inNav: true,
    navGroup: 'commerce',
    parentNav: commandCenterParent,
    skeleton: 'list',
    breadcrumbLabelKey: 'nav.payments',
  },
];
