import { COMMAND_CENTER_PATH, type AppRouteDefinition } from './routes.types';

/** Core overview routes — command center, workstream, goals, approvals, insights, agents, timeline. */
export const coreRoutes: AppRouteDefinition[] = [
  {
    path: COMMAND_CENTER_PATH,
    module: 'command-center',
    sidebarGroup: 'home',
    layout: 'overview',
    inNav: true,
    skeleton: 'command-center',
    breadcrumbLabelKey: 'nav.commandCenter',
  },
  {
    path: '/',
    module: 'command-center',
    sidebarGroup: 'home',
    layout: 'overview',
    redirectTo: COMMAND_CENTER_PATH,
  },
  {
    path: '/home',
    module: 'command-center',
    sidebarGroup: 'home',
    layout: 'overview',
    redirectTo: COMMAND_CENTER_PATH,
  },
  {
    path: '/cockpit',
    module: 'command-center',
    sidebarGroup: 'home',
    layout: 'overview',
    redirectTo: COMMAND_CENTER_PATH,
  },
  {
    path: '/overview',
    module: 'aether-overview',
    sidebarGroup: 'overview',
    layout: 'overview',
    inNav: true,
    skeleton: 'module',
    breadcrumbLabelKey: 'nav.overview',
  },
  {
    path: '/aether-overview',
    module: 'aether-overview',
    sidebarGroup: 'overview',
    layout: 'overview',
    redirectTo: '/overview',
  },
  {
    path: '/workstream',
    module: 'workstream',
    sidebarGroup: 'overview',
    layout: 'overview',
    inNav: true,
    skeleton: 'module',
    breadcrumbLabelKey: 'nav.workstream',
  },
  {
    path: '/goals',
    module: 'goals',
    sidebarGroup: 'overview',
    layout: 'overview',
    inNav: true,
    skeleton: 'module',
    breadcrumbLabelKey: 'nav.goals',
  },
  {
    path: '/goals/:id',
    module: 'goals',
    sidebarGroup: 'overview',
    layout: 'overview',
    parentNav: { to: '/goals', labelKey: 'nav.goals' },
    skeleton: 'module',
    breadcrumbLabelKey: 'goals.detail.title',
  },
  {
    path: '/approvals',
    module: 'approvals',
    sidebarGroup: 'overview',
    layout: 'overview',
    inNav: true,
    skeleton: 'list',
    breadcrumbLabelKey: 'nav.approvals',
  },
  {
    path: '/insights',
    module: 'insights',
    sidebarGroup: 'overview',
    layout: 'overview',
    inNav: true,
    skeleton: 'module',
    breadcrumbLabelKey: 'nav.insights',
  },
  {
    path: '/agents',
    module: 'agents',
    sidebarGroup: 'overview',
    layout: 'overview',
    inNav: true,
    skeleton: 'list',
    breadcrumbLabelKey: 'nav.agents',
  },
  {
    path: '/timeline',
    module: 'timeline',
    sidebarGroup: 'overview',
    layout: 'overview',
    inNav: true,
    skeleton: 'list',
    breadcrumbLabelKey: 'nav.timeline',
  },
  {
    path: '/notifications',
    module: 'timeline',
    sidebarGroup: 'overview',
    layout: 'overview',
    inNav: true,
    skeleton: 'list',
    breadcrumbLabelKey: 'nav.notifications',
  },
  {
    path: '/activity',
    module: 'timeline',
    sidebarGroup: 'overview',
    layout: 'overview',
    redirectTo: '/timeline',
  },
  {
    path: '/history',
    module: 'timeline',
    sidebarGroup: 'overview',
    layout: 'overview',
    redirectTo: '/timeline',
  },
  {
    path: '/dashboard',
    module: 'command-center',
    sidebarGroup: 'deep',
    layout: 'overview',
    redirectTo: COMMAND_CENTER_PATH,
  },
];
