import { Router } from 'express';
import { AdminController } from './api/controllers/AdminController';
import { BrainController } from './api/controllers/BrainController';
import { ObservabilityController } from './api/controllers/ObservabilityController';

const router = Router();
const controller = new AdminController();
const brainController = new BrainController();
const observability = new ObservabilityController();

router.post('/command', ...controller.executeCommand);
router.get('/command/:commandId/agent-run', ...controller.getAgentRun);
router.post('/command/:commandId/agent-run/resume', ...controller.resumeAgentRun);
router.post('/command/:commandId/agent-run/cancel', ...controller.cancelAgentRun);
router.post('/command/tools/execute', ...controller.executeBrainTool);
router.post('/command/tools/reject', ...controller.rejectBrainTool);
router.post('/command/:commandId/undo', ...controller.undoCommand);
router.get('/suggestions', ...controller.getSuggestions);
router.post('/ui-event', ...controller.recordUiEvent);
router.get('/dashboard', ...controller.getDashboardSummary);
router.get('/commands', ...controller.getCommandHistory);
router.get('/activity', ...controller.getActivityFeed);
router.get('/notifications', ...controller.getNotifications);
router.patch('/notifications/:id/read', ...controller.markNotificationRead);
router.post('/notifications/mark-all-read', ...controller.markAllNotificationsRead);
router.delete('/notifications/:id', ...controller.dismissNotification);
router.get('/workflows/:runId', ...controller.getWorkflowTrace);
router.get('/autonomy', ...controller.getAutonomyMetrics);
router.get('/autonomy/trace', ...controller.getAutonomyTrace);
router.get('/explain', ...controller.getExplainability);
router.get('/truth-status', ...controller.getTruthStatus);
router.get('/operating-metrics', ...controller.getOperatingMetrics);
router.get('/policies/approval', ...controller.getApprovalPolicy);
router.put('/policies/approval', ...controller.updateApprovalPolicy);
router.get('/settings', ...controller.getSettings);
router.put('/settings', ...controller.updateSettings);
router.get('/connected-services', ...controller.getConnectedServices);
router.get('/events/stream', ...controller.streamEvents);
router.post('/truth-review', ...controller.completeTruthReview);
router.get('/observability/status', ...observability.getStatus);
router.post('/observability/probe-error', ...observability.probeError);
router.get('/brain/collective-insights', ...brainController.getCollectiveInsights);
router.get('/brain/global-knowledge/status', ...brainController.getGlobalKnowledgeStatus);
router.get('/brain/global-knowledge/sync-history', ...brainController.getGlobalKnowledgeSyncHistory);
router.get('/brain/global-patches/active', ...brainController.listActiveGlobalPatches);
router.get('/brain/contribution-history', ...brainController.getContributionHistory);
router.get('/brain/contribution-summary', ...brainController.getContributionSummary);
router.get('/brain/global-patches', ...brainController.listGlobalPatches);
router.post('/brain/global-patches', ...brainController.createGlobalPatch);
router.put('/brain/global-patches/:id', ...brainController.updateGlobalPatch);
router.post('/brain/global-patches/:id/publish', ...brainController.publishGlobalPatch);
router.post('/brain/global-patches/:id/retire', ...brainController.retireGlobalPatch);
router.get('/brain/lora', ...brainController.getLoRAAdapters);
router.put('/brain/lora', ...brainController.upsertLoRAAdapter);
router.get('/brain/export', ...brainController.exportBrain);
router.post('/brain/import', ...brainController.importBrain);
router.get('/brain/memory/summary', ...brainController.getMemorySummary);
router.get('/brain/memory/entries', ...brainController.listMemoryEntries);
router.delete('/brain/memory/entries/:id', ...brainController.deleteMemoryEntry);
router.post('/brain/memory/clear-short-term', ...brainController.clearShortTermMemory);
router.post('/brain/memory/consolidate', ...brainController.consolidateMemory);
router.get('/brain/reflections/timeline', ...brainController.getReflectionTimeline);
router.get('/brain/reflection-experiments', ...brainController.listReflectionExperiments);
router.post('/brain/reflection-experiments', ...brainController.createReflectionExperiment);
router.post('/brain/reflection-experiments/:id/stop', ...brainController.stopReflectionExperiment);
router.get('/brain/reflection-experiments/:id/outcomes', ...brainController.getReflectionExperimentOutcomes);

export default router;
