import { Router } from 'express';
import { AdminController } from './api/controllers/AdminController';
import { BrainController } from './api/controllers/BrainController';
import { ObservabilityController } from './api/controllers/ObservabilityController';
import { FederatedDeploymentsController } from './api/controllers/FederatedDeploymentsController';

const router = Router();
const controller = new AdminController();
const brainController = new BrainController();
const observability = new ObservabilityController();
const federatedDeployments = new FederatedDeploymentsController();

router.post('/command', ...controller.executeCommand);
router.get('/command/:commandId/agent-run', ...controller.getAgentRun);
router.post('/command/:commandId/agent-run/resume', ...controller.resumeAgentRun);
router.post('/command/:commandId/agent-run/cancel', ...controller.cancelAgentRun);
router.post('/command/tools/execute', ...controller.executeBrainTool);
router.post('/command/tools/reject', ...controller.rejectBrainTool);
router.post('/command/:commandId/undo', ...controller.undoCommand);
router.get('/suggestions', ...controller.getSuggestions);
router.get('/proactive-suggestions', ...controller.getProactiveSuggestions);
router.post('/proactive-suggestions/:id/dismiss', ...controller.dismissProactiveSuggestion);
router.post('/proactive-suggestions/:id/snooze', ...controller.snoozeProactiveSuggestion);
router.post('/proactive-suggestions/:id/execute', ...controller.executeProactiveSuggestion);
router.post('/ui-event', ...controller.recordUiEvent);
router.get('/dashboard', ...controller.getDashboardSummary);
router.get('/commands', ...controller.getCommandHistory);
router.get('/commands/:runId/shared-memory', ...controller.getRunSharedMemory);
router.get('/activity', ...controller.getActivityFeed);
router.get('/overview', ...controller.getOverviewFeed);
router.get('/overview/handoffs', ...controller.getOverviewHandoffs);
router.get('/agents/metrics', ...controller.getAgentMetrics);
router.get('/agents', ...controller.getAgentsRoster);
router.get('/agents/:agentKey/activity', ...controller.getAgentActivity);
router.get('/notifications', ...controller.getNotifications);
router.get('/notifications/push/vapid-key', ...controller.getWebPushVapidKey);
router.post('/notifications/push/subscribe', ...controller.subscribeWebPush);
router.post('/notifications/push/unsubscribe', ...controller.unsubscribeWebPush);
router.patch('/notifications/:id/read', ...controller.markNotificationRead);
router.post('/notifications/mark-all-read', ...controller.markAllNotificationsRead);
router.delete('/notifications/:id', ...controller.dismissNotification);
router.get('/workflows/:runId', ...controller.getWorkflowTrace);
router.get('/autonomy', ...controller.getAutonomyMetrics);
router.get('/autonomy/trace', ...controller.getAutonomyTrace);
router.get('/explain', ...controller.getExplainability);
router.get('/explain/diff', ...controller.getExplainabilityDiff);
router.get('/explain/export', ...controller.exportExplainability);
router.get('/explain/audit-export', ...controller.auditExportExplainability);
router.get('/truth-status', ...controller.getTruthStatus);
router.get('/operating-metrics', ...controller.getOperatingMetrics);
router.get('/policies/approval', ...controller.getApprovalPolicy);
router.put('/policies/approval', ...controller.updateApprovalPolicy);
router.post('/autonomy/simulate', ...controller.simulateAutonomy);
router.get('/settings', ...controller.getSettings);
router.put('/settings', ...controller.updateSettings);
router.get('/connected-services', ...controller.getConnectedServices);
router.get('/goals/suggestions', ...controller.listAiGoalSuggestions);
router.get('/goals/conflicts', ...controller.getGoalConflicts);
router.post('/goals/plan', ...controller.buildGoalPlan);
router.get('/goals/plan/active', ...controller.getActiveGoalPlan);
router.post('/goals/suggestions/:id/accept', ...controller.acceptAiGoalSuggestion);
router.post('/goals/suggestions/:id/dismiss', ...controller.dismissAiGoalSuggestion);
router.get('/goals', ...controller.listGoals);
router.get('/goals/:id', ...controller.getGoal);
router.post('/goals', ...controller.createGoal);
router.put('/goals/:id', ...controller.updateGoal);
router.delete('/goals/:id', ...controller.deleteGoal);
router.post('/goals/:id/refresh', ...controller.refreshGoal);
router.get('/goals/:id/suggestions', ...controller.getGoalSuggestions);
router.get('/events/stream', ...controller.streamEvents);
router.post('/truth-review', ...controller.completeTruthReview);
router.get('/observability/status', ...observability.getStatus);
router.post('/observability/probe-error', ...observability.probeError);
router.get('/federated/deployments', ...federatedDeployments.list);
router.get('/federated/deployments/status', ...federatedDeployments.status);
router.post('/federated/deployments', ...federatedDeployments.create);
router.put('/federated/deployments/:deploymentId', ...federatedDeployments.update);
router.delete('/federated/deployments/:deploymentId', ...federatedDeployments.deactivate);
router.get('/brain/collective-insights', ...brainController.getCollectiveInsights);
router.get('/brain/global-knowledge/status', ...brainController.getGlobalKnowledgeStatus);
router.get('/brain/global-knowledge/sync-history', ...brainController.getGlobalKnowledgeSyncHistory);
router.get('/brain/global-patches/active', ...brainController.listActiveGlobalPatches);
router.get('/brain/contribution-history', ...brainController.getContributionHistory);
router.get('/brain/contribution-summary', ...brainController.getContributionSummary);
router.get('/brain/global-patches', ...brainController.listGlobalPatches);
router.post('/brain/global-patches', ...brainController.createGlobalPatch);
router.put('/brain/global-patches/:id', ...brainController.updateGlobalPatch);
router.post('/brain/global-patches/:id/publish', ...brainController.publishGlobalPatch);
router.post('/brain/global-patches/:id/retire', ...brainController.retireGlobalPatch);
router.get('/brain/lora', ...brainController.getLoRAAdapters);
router.put('/brain/lora', ...brainController.upsertLoRAAdapter);
router.get('/brain/export', ...brainController.exportBrain);
router.post('/brain/import', ...brainController.importBrain);
router.get('/brain/memory/summary', ...brainController.getMemorySummary);
router.get('/brain/memory/entries', ...brainController.listMemoryEntries);
router.delete('/brain/memory/entries/:id', ...brainController.deleteMemoryEntry);
router.post('/brain/memory/clear-short-term', ...brainController.clearShortTermMemory);
router.post('/brain/memory/consolidate', ...brainController.consolidateMemory);
router.get('/brain/reflections/timeline', ...brainController.getReflectionTimeline);
router.get('/brain/reflection-experiments', ...brainController.listReflectionExperiments);
router.post('/brain/reflection-experiments', ...brainController.createReflectionExperiment);
router.post('/brain/reflection-experiments/:id/stop', ...brainController.stopReflectionExperiment);
router.get('/brain/reflection-experiments/:id/outcomes', ...brainController.getReflectionExperimentOutcomes);

export default router;
