export class EmailMessage {
  constructor(
    public readonly id: string,
    public from: string,
    public subject: string | null,
    public body: string | null,
    public status: string, // received, processed, replied, escalated
    public riskLevel: string | null, // low, high
    public readonly createdAt: Date
  ) {}

  static create(data: {
    from: string;
    subject?: string;
    body?: string;
  }): EmailMessage {
    return new EmailMessage(
      '', // ID generated by DB
      data.from,
      data.subject || null,
      data.body || null,
      'received',
      null,
      new Date()
    );
  }

  markAsProcessed(riskLevel: string): void {
    this.status = 'processed';
    this.riskLevel = riskLevel;
  }

  markAsReplied(): void {
    this.status = 'replied';
  }

  escalate(): void {
    this.status = 'escalated';
    this.riskLevel = 'high';
  }
}