import type { ActivityItem, ActivityPeriod } from '@/types/activity';

function daysAgo(days: number, hour = 10, minute = 0): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

function item(partial: Omit<ActivityItem, 'source' | 'searchText'> & { id: string }): ActivityItem {
  const searchText = [
    partial.actionLabel,
    partial.description,
    partial.module,
    partial.actionType,
    partial.impact?.value,
    partial.details?.productName,
    partial.details?.supplierName,
  ]
    .filter(Boolean)
    .join(' ')
    .toLowerCase();
  return { ...partial, source: 'demo', searchText };
}

const DEMO_ITEMS: ActivityItem[] = [
  item({
    id: 'demo-1',
    at: daysAgo(0, 8, 15),
    actionType: 'autonomy_execute',
    actionLabel: 'Autonome sync',
    description: 'Voorraad en prijzen gesynchroniseerd met Shopify (142 SKU)',
    module: 'inventory-pricing',
    category: 'sync',
    risk: 'low',
    status: 'autonomous',
    executor: 'aether',
    impact: { label: 'Volume', value: '142 SKU' },
    confidence: 0.94,
    rationale:
      'Lage risico-sync binnen policy: geen prijswijziging boven 3%, voorraad binnen drempels.',
    details: { productCount: 142, channel: 'Shopify' },
  }),
  item({
    id: 'demo-2',
    at: daysAgo(0, 11, 42),
    actionType: 'price_adjusted',
    actionLabel: 'Prijsaanpassing',
    description: 'Outdoor & camping: +2,1% marge op 12 producten na vraagpiek',
    module: 'inventory-pricing',
    category: 'pricing',
    risk: 'low',
    status: 'autonomous',
    executor: 'aether',
    impact: { label: 'Marge', value: '+2,1%' },
    confidence: 0.91,
    rationale: 'Seizoensvraag + concurrentie-index onder drempel; automatisch toegepast.',
    related: { type: 'insight', id: 'insight-outdoor-margin' },
    details: { productName: 'Outdoor & camping', skuCount: 12 },
  }),
  item({
    id: 'demo-3',
    at: daysAgo(1, 9, 5),
    actionType: 'approved',
    actionLabel: 'Goedgekeurd',
    description: 'Terugbetaling € 89,50 goedgekeurd en uitgevoerd',
    module: 'payment-fulfillment',
    category: 'approval',
    risk: 'high',
    status: 'approved',
    executor: 'merchant',
    impact: { label: 'Bedrag', value: '€ 89,50' },
    confidence: 0.72,
    rationale: 'Klanttevredenheid prioriteit; order #4821 binnen retourbeleid.',
    related: { type: 'approval', id: 'demo-approval-refund-1' },
    details: { orderId: '4821', amount: 89.5 },
  }),
  item({
    id: 'demo-4',
    at: daysAgo(1, 14, 20),
    actionType: 'supplier_price_changed_received',
    actionLabel: 'Leverancierscheck',
    description: 'Nordic Supply Co.: inkoopprijs +3,8% — marge-impact geanalyseerd',
    module: 'supplier-intelligence',
    category: 'supplier',
    risk: 'low',
    status: 'autonomous',
    executor: 'aether',
    impact: { label: 'Leverancier', value: 'Nordic Supply Co.' },
    confidence: 0.88,
    rationale: "Automatische herberekening verkoopprijzen voor 28 gekoppelde SKU's.",
    details: { supplierName: 'Nordic Supply Co.', deltaPct: 3.8 },
  }),
  item({
    id: 'demo-5',
    at: daysAgo(1, 16, 55),
    actionType: 'email.auto_reply',
    actionLabel: 'Automatisch antwoord',
    description: 'Levertijd-vraag beantwoord (template: verzending NL)',
    module: 'aether-mail',
    category: 'mail',
    risk: 'low',
    status: 'autonomous',
    executor: 'aether',
    confidence: 0.86,
    rationale: 'Categorie FAQ; geen commerciële toezegging buiten beleid.',
    related: { type: 'email', id: 'demo-email-1' },
    details: { subject: 'Wanneer wordt mijn order verzonden?' },
  }),
  item({
    id: 'demo-6',
    at: daysAgo(2, 10, 30),
    actionType: 'rejected',
    actionLabel: 'Afgewezen',
    description: 'Bulkkorting 15% op keukenlijn afgewezen door merchant',
    module: 'approval',
    category: 'approval',
    risk: 'high',
    status: 'rejected',
    executor: 'merchant',
    impact: { label: 'Marge', value: '−15% voorgesteld' },
    confidence: 0.61,
    rationale: 'Onder minimale marge-drempel voor categorie keuken & koken.',
    related: { type: 'approval', id: 'demo-approval-discount-1' },
  }),
  item({
    id: 'demo-7',
    at: daysAgo(2, 13, 0),
    actionType: 'command_executed',
    actionLabel: 'NL-commando',
    description: 'PRICE_ADJUST: Verhoog marge outdoor categorie met 2%',
    module: 'admin-command-bar',
    category: 'command',
    risk: 'low',
    status: 'info',
    executor: 'merchant',
    confidence: 0.88,
    rationale: '12 SKU bijgewerkt; resultaat binnen policy-limiet.',
  }),
  item({
    id: 'demo-8',
    at: daysAgo(3, 7, 45),
    actionType: 'autonomy_execute',
    actionLabel: 'Autonome sync',
    description: 'Nachtelijke catalogus-sync voltooid (0 conflicten)',
    module: 'inventory-pricing',
    category: 'sync',
    risk: 'none',
    status: 'autonomous',
    executor: 'aether',
    impact: { label: 'Status', value: '0 conflicten' },
    confidence: 0.97,
  }),
  item({
    id: 'demo-9',
    at: daysAgo(3, 12, 10),
    actionType: 'outcome_verified_with_evidence',
    actionLabel: 'Uitkomst geverifieerd',
    description: 'Omzet uplift outdoor categorie geverifieerd (+€ 1.240, 30d)',
    module: 'outcomes',
    category: 'outcome',
    risk: 'none',
    status: 'info',
    executor: 'aether',
    impact: { label: 'Uplift', value: '€ 1.240' },
    confidence: 0.9,
    related: { type: 'insight', id: 'insight-outdoor-uplift' },
  }),
  item({
    id: 'demo-10',
    at: daysAgo(4, 9, 20),
    actionType: 'mail_approval_required_received',
    actionLabel: 'Goedkeuring aangevraagd',
    description: 'Escalatie: klacht leververtraging — handmatige compensatie voorgesteld',
    module: 'aether-mail',
    category: 'mail',
    risk: 'high',
    status: 'pending',
    executor: 'aether',
    confidence: 0.55,
    related: { type: 'approval', id: 'demo-approval-mail-1' },
  }),
  item({
    id: 'demo-11',
    at: daysAgo(4, 15, 40),
    actionType: 'price_adjusted',
    actionLabel: 'Prijsaanpassing',
    description: 'Woonaccessoires: dynamische prijs +1,4% (concurrentie-match)',
    module: 'inventory-pricing',
    category: 'pricing',
    risk: 'low',
    status: 'autonomous',
    executor: 'aether',
    impact: { label: 'Marge', value: '+1,4%' },
    confidence: 0.89,
    details: { productName: 'Woonaccessoires', skuCount: 8 },
  }),
  item({
    id: 'demo-12',
    at: daysAgo(5, 11, 5),
    actionType: 'email_rolled_back',
    actionLabel: 'E-mail teruggedraaid',
    description: 'Auto-reply teruggedraaid na merchant review (onjuiste levertijd)',
    module: 'aether-mail',
    category: 'mail',
    risk: 'high',
    status: 'info',
    executor: 'merchant',
    rationale: 'Template verouderd na beleidswijziging verzending.',
    related: { type: 'email', id: 'demo-email-2' },
  }),
  item({
    id: 'demo-13',
    at: daysAgo(5, 14, 30),
    actionType: 'negotiation_started',
    actionLabel: 'Onderhandeling',
    description: 'Inkoopvoorstel gestart met Alpine Parts GmbH',
    module: 'agentic-commerce',
    category: 'supplier',
    risk: 'low',
    status: 'info',
    executor: 'aether',
    details: { supplierName: 'Alpine Parts GmbH' },
  }),
  item({
    id: 'demo-14',
    at: daysAgo(6, 8, 0),
    actionType: 'autonomy_execute',
    actionLabel: 'Autonoom uitgevoerd',
    description: 'Low-risk mail: 6 FAQ-antwoorden verzonden',
    module: 'aether-mail',
    category: 'mail',
    risk: 'low',
    status: 'autonomous',
    executor: 'aether',
    impact: { label: 'Volume', value: '6 mails' },
    confidence: 0.92,
  }),
  item({
    id: 'demo-15',
    at: daysAgo(7, 10, 15),
    actionType: 'approved',
    actionLabel: 'Goedgekeurd',
    description: 'Prijsverhoging keukenlijn +4% goedgekeurd (18 SKU)',
    module: 'approval',
    category: 'approval',
    risk: 'high',
    status: 'approved',
    executor: 'merchant',
    impact: { label: 'Marge', value: '+4%' },
    confidence: 0.78,
    related: { type: 'approval', id: 'demo-approval-price-1' },
  }),
  item({
    id: 'demo-16',
    at: daysAgo(8, 16, 45),
    actionType: 'command_executed',
    actionLabel: 'NL-commando',
    description: 'SHOW_LOW_MARGIN: 9 producten onder 22% marge',
    module: 'admin-command-bar',
    category: 'command',
    risk: 'none',
    status: 'info',
    executor: 'merchant',
    confidence: 0.95,
  }),
  item({
    id: 'demo-17',
    at: daysAgo(9, 9, 30),
    actionType: 'autonomy_execute',
    actionLabel: 'Autonome sync',
    description: 'Leveranciersfeed verwerkt: 3 prijswijzigingen toegepast',
    module: 'supplier-intelligence',
    category: 'supplier',
    risk: 'low',
    status: 'autonomous',
    executor: 'aether',
    confidence: 0.9,
  }),
  item({
    id: 'demo-18',
    at: daysAgo(10, 13, 20),
    actionType: 'price_adjusted',
    actionLabel: 'Prijsaanpassing',
    description: 'Keuken & koken: bundelprijs geoptimaliseerd (−2% op slow movers)',
    module: 'inventory-pricing',
    category: 'pricing',
    risk: 'low',
    status: 'autonomous',
    executor: 'aether',
    impact: { label: 'Volume', value: '5 SKU' },
    confidence: 0.87,
    details: { productName: 'Keuken & koken' },
  }),
  item({
    id: 'demo-19',
    at: daysAgo(11, 7, 50),
    actionType: 'payment_processed',
    actionLabel: 'Betaling verwerkt',
    description: 'Batch uitbetaling leveranciers voltooid (€ 24.180)',
    module: 'payment-fulfillment',
    category: 'outcome',
    risk: 'none',
    status: 'info',
    executor: 'aether',
    impact: { label: 'Bedrag', value: '€ 24.180' },
  }),
  item({
    id: 'demo-20',
    at: daysAgo(12, 11, 0),
    actionType: 'autonomy_decide',
    actionLabel: 'Beslissing',
    description: 'Seizoenspromotie outdoor: uitgesteld tot voorraad > 80%',
    module: 'autonomy',
    category: 'pricing',
    risk: 'low',
    status: 'autonomous',
    executor: 'aether',
    confidence: 0.84,
    rationale: 'Voorraaddrempel niet gehaald; herbeoordeling over 48u.',
  }),
  item({
    id: 'demo-21',
    at: daysAgo(13, 14, 10),
    actionType: 'email_processed',
    actionLabel: 'E-mail verwerkt',
    description: 'Inkomende RFQ groothandel — doorgestuurd naar onderhandeling',
    module: 'aether-mail',
    category: 'mail',
    risk: 'low',
    status: 'info',
    executor: 'aether',
    related: { type: 'email', id: 'demo-email-3' },
  }),
  item({
    id: 'demo-22',
    at: daysAgo(14, 9, 5),
    actionType: 'autonomy_execute',
    actionLabel: 'Autonoom uitgevoerd',
    description: 'Retourlabel gegenereerd voor order #4798 (low-risk)',
    module: 'payment-fulfillment',
    category: 'sync',
    risk: 'low',
    status: 'autonomous',
    executor: 'aether',
    confidence: 0.93,
  }),
  item({
    id: 'demo-23',
    at: daysAgo(15, 10, 40),
    actionType: 'rejected',
    actionLabel: 'Afgewezen',
    description: 'Automatische prijsverlaging campinglijn afgewezen',
    module: 'approval',
    category: 'approval',
    risk: 'high',
    status: 'rejected',
    executor: 'merchant',
    rationale: 'Minimale verkoopprijs zou worden overschreden op 4 SKU.',
    related: { type: 'approval', id: 'demo-approval-price-2' },
  }),
  item({
    id: 'demo-24',
    at: daysAgo(16, 8, 25),
    actionType: 'command_executed',
    actionLabel: 'NL-commando',
    description: 'SUPPLIER_STATUS: Overzicht Nordic Supply en Alpine Parts',
    module: 'admin-command-bar',
    category: 'command',
    risk: 'none',
    status: 'info',
    executor: 'merchant',
    confidence: 0.91,
  }),
  item({
    id: 'demo-25',
    at: daysAgo(17, 15, 0),
    actionType: 'outcome_verified_with_evidence',
    actionLabel: 'Uitkomst geverifieerd',
    description: 'Tijd bespaard door mail-autonomie: 4,2 uur (7d)',
    module: 'outcomes',
    category: 'outcome',
    risk: 'none',
    status: 'info',
    executor: 'aether',
    impact: { label: 'Tijd', value: '4,2 uur' },
    related: { type: 'insight', id: 'insight-time-saved' },
  }),
  item({
    id: 'demo-26',
    at: daysAgo(18, 12, 30),
    actionType: 'price_adjusted',
    actionLabel: 'Prijsaanpassing',
    description: 'Outdoor & camping: weekendprijs +3% (autonoom, binnen band)',
    module: 'inventory-pricing',
    category: 'pricing',
    risk: 'low',
    status: 'autonomous',
    executor: 'aether',
    impact: { label: 'Marge', value: '+3%' },
    confidence: 0.9,
  }),
  item({
    id: 'demo-27',
    at: daysAgo(19, 9, 15),
    actionType: 'autonomy_measure',
    actionLabel: 'Meting',
    description: 'Weekrapport autonomie: 214 acties, 87 low-risk zonder gate',
    module: 'autonomy',
    category: 'outcome',
    risk: 'none',
    status: 'info',
    executor: 'aether',
    related: { type: 'insight', id: 'insight-autonomy-week' },
  }),
  item({
    id: 'demo-28',
    at: daysAgo(20, 11, 45),
    actionType: 'approved',
    actionLabel: 'Goedgekeurd',
    description: 'Vervangend product verzonden — goedgekeurde compensatie',
    module: 'approval',
    category: 'approval',
    risk: 'high',
    status: 'approved',
    executor: 'merchant',
    confidence: 0.74,
    related: { type: 'approval', id: 'demo-approval-replace-1' },
  }),
  item({
    id: 'demo-29',
    at: daysAgo(21, 7, 0),
    actionType: 'autonomy_execute',
    actionLabel: 'Autonome sync',
    description: 'Multi-channel voorraad gelijkgetrokken (Bol + eigen shop)',
    module: 'inventory-pricing',
    category: 'sync',
    risk: 'low',
    status: 'autonomous',
    executor: 'aether',
    impact: { label: 'Kanalen', value: '2' },
    confidence: 0.96,
  }),
  item({
    id: 'demo-30',
    at: daysAgo(22, 14, 5),
    actionType: 'supplier_price_changed_received',
    actionLabel: 'Leverancierscheck',
    description: 'Alpine Parts: levertijd +2 dagen — geen prijsactie nodig',
    module: 'supplier-intelligence',
    category: 'supplier',
    risk: 'none',
    status: 'info',
    executor: 'aether',
    details: { supplierName: 'Alpine Parts GmbH' },
  }),
  item({
    id: 'demo-31',
    at: daysAgo(23, 10, 20),
    actionType: 'email.auto_reply',
    actionLabel: 'Automatisch antwoord',
    description: 'Retourinstructies verstuurd (policy-conform)',
    module: 'aether-mail',
    category: 'mail',
    risk: 'low',
    status: 'autonomous',
    executor: 'aether',
    confidence: 0.88,
  }),
  item({
    id: 'demo-32',
    at: daysAgo(24, 13, 50),
    actionType: 'command_executed',
    actionLabel: 'NL-commando',
    description: 'APPROVALS_PENDING: 2 open high-risk goedkeuringen',
    module: 'admin-command-bar',
    category: 'command',
    risk: 'high',
    status: 'info',
    executor: 'merchant',
    confidence: 0.82,
  }),
  item({
    id: 'demo-33',
    at: daysAgo(25, 8, 40),
    actionType: 'autonomy_execute',
    actionLabel: 'Autonoom uitgevoerd',
    description: 'Dead stock markering: 7 SKU naar outlet-prijs',
    module: 'inventory-pricing',
    category: 'pricing',
    risk: 'low',
    status: 'autonomous',
    executor: 'aether',
    impact: { label: 'SKU', value: '7' },
    confidence: 0.85,
  }),
  item({
    id: 'demo-34',
    at: daysAgo(26, 16, 10),
    actionType: 'action_executed',
    actionLabel: 'Actie uitgevoerd',
    description: 'Goedgekeurde prijsupdate campinglijn uitgevoerd',
    module: 'approval',
    category: 'approval',
    risk: 'high',
    status: 'approved',
    executor: 'aether',
    related: { type: 'approval', id: 'demo-approval-price-3' },
  }),
  item({
    id: 'demo-35',
    at: daysAgo(27, 9, 55),
    actionType: 'negotiation_started',
    actionLabel: 'Onderhandeling',
    description: 'Volume-korting onderhandeling Nordic Supply (doel −2% inkoop)',
    module: 'agentic-commerce',
    category: 'supplier',
    risk: 'low',
    status: 'pending',
    executor: 'aether',
    details: { supplierName: 'Nordic Supply Co.' },
  }),
  item({
    id: 'demo-36',
    at: daysAgo(28, 11, 30),
    actionType: 'autonomy_observe',
    actionLabel: 'Observatie',
    description: 'Piekvraag gedetecteerd: tuin & outdoor (+34% views 48u)',
    module: 'autonomy',
    category: 'outcome',
    risk: 'none',
    status: 'info',
    executor: 'aether',
    related: { type: 'insight', id: 'insight-garden-peak' },
  }),
  item({
    id: 'demo-37',
    at: daysAgo(29, 7, 15),
    actionType: 'price_adjusted',
    actionLabel: 'Prijsaanpassing',
    description: 'Tuin & outdoor: +2,8% marge (12 SKU, autonoom)',
    module: 'inventory-pricing',
    category: 'pricing',
    risk: 'low',
    status: 'autonomous',
    executor: 'aether',
    impact: { label: 'Marge', value: '+2,8%' },
    confidence: 0.9,
    details: { productName: 'Tuin & outdoor' },
  }),
  item({
    id: 'demo-38',
    at: daysAgo(29, 14, 0),
    actionType: 'approved',
    actionLabel: 'Goedgekeurd',
    description: 'Spoedverzending kosten vergoed voor order #4755',
    module: 'payment-fulfillment',
    category: 'approval',
    risk: 'high',
    status: 'approved',
    executor: 'merchant',
    impact: { label: 'Bedrag', value: '€ 12,95' },
    related: { type: 'approval', id: 'demo-approval-ship-1' },
  }),
  item({
    id: 'demo-39',
    at: daysAgo(30, 10, 0),
    actionType: 'autonomy_execute',
    actionLabel: 'Autonome sync',
    description: 'Maandelijkse catalogus-backup en integriteitscheck OK',
    module: 'inventory-pricing',
    category: 'sync',
    risk: 'none',
    status: 'autonomous',
    executor: 'aether',
    confidence: 0.98,
  }),
  item({
    id: 'demo-40',
    at: daysAgo(30, 15, 30),
    actionType: 'outcome_verified_with_evidence',
    actionLabel: 'Uitkomst geverifieerd',
    description: 'Margin improvement 30d: +2,1% geverifieerd met evidence',
    module: 'outcomes',
    category: 'outcome',
    risk: 'none',
    status: 'info',
    executor: 'aether',
    impact: { label: 'Marge', value: '+2,1%' },
    related: { type: 'insight', id: 'insight-margin-30d' },
  }),
];

export function getActivityDemoItems(): ActivityItem[] {
  return [...DEMO_ITEMS].sort((a, b) => new Date(b.at).getTime() - new Date(a.at).getTime());
}

export function periodToDays(period: ActivityPeriod): number {
  switch (period) {
    case 'today':
      return 1;
    case '7d':
      return 7;
    case '30d':
      return 30;
    case 'custom':
      return 30;
    default:
      return 30;
  }
}

let liveActivityCounter = 0;

/** Ephemeral activity row for live-demo bus events */
export function createLiveActivityItem(): ActivityItem {
  liveActivityCounter += 1;
  return item({
    id: `live-${Date.now()}-${liveActivityCounter}`,
    at: new Date().toISOString(),
    actionType: 'autonomy_execute',
    actionLabel: 'Autonome sync',
    description: 'Voorraad en prijzen gesynchroniseerd met Shopify (142 SKU)',
    module: 'inventory-pricing',
    category: 'sync',
    risk: 'low',
    status: 'autonomous',
    executor: 'aether',
    impact: { label: 'Volume', value: '142 SKU' },
    confidence: 0.94,
    rationale:
      'Lage risico-sync binnen policy: geen prijswijziging boven 3%, voorraad binnen drempels.',
    details: { productCount: 142, channel: 'Shopify' },
  });
}

export function filterDemoByPeriod(
  items: ActivityItem[],
  period: ActivityPeriod,
  custom?: { from: string; to: string },
): ActivityItem[] {
  const now = new Date();
  let since: Date;
  if (period === 'custom' && custom?.from) {
    since = new Date(custom.from);
  } else if (period === 'today') {
    since = new Date();
    since.setHours(0, 0, 0, 0);
  } else {
    since = new Date();
    since.setDate(since.getDate() - periodToDays(period));
    since.setHours(0, 0, 0, 0);
  }
  const until = period === 'custom' && custom?.to ? new Date(custom.to) : now;
  return items.filter((i) => {
    const d = new Date(i.at);
    return d >= since && d <= until;
  });
}
